enum PushScreenType {
  login,
  forgotPassword,
  otp,
  changePassword,
  createCode,
  home,
  notification,
  profile,
  setting,
  viewCode,
  viewFollowupAppointment,
  viewHealthInsurance,
  viewMedicalRecord,
  viewPrescription,
  viewTransferLetter,
  changePhoneNumber,
  otpAuthPhone
}