// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMwyPFkVe8BcX5bJMaS0h0NiG_XRxPg4o',
    appId: '1:830041646492:web:8c56952a32ace66718d459',
    messagingSenderId: '830041646492',
    projectId: 'flutter-app-8662f',
    authDomain: 'flutter-app-8662f.firebaseapp.com',
    storageBucket: 'flutter-app-8662f.firebasestorage.app',
    measurementId: 'G-C60MY22WQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACLhSwpdi-o-lZ7vyQ3eA1j5TXNgCLj-A',
    appId: '1:830041646492:android:bcca52cc76c9ae4418d459',
    messagingSenderId: '830041646492',
    projectId: 'flutter-app-8662f',
    storageBucket: 'flutter-app-8662f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9SPDkDLTQy_yJ-RFFoyAXyiBP3NU-1hk',
    appId: '1:830041646492:ios:f53e77a9cdb2126618d459',
    messagingSenderId: '830041646492',
    projectId: 'flutter-app-8662f',
    storageBucket: 'flutter-app-8662f.firebasestorage.app',
    iosBundleId: 'com.example.interHospitalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9SPDkDLTQy_yJ-RFFoyAXyiBP3NU-1hk',
    appId: '1:830041646492:ios:f53e77a9cdb2126618d459',
    messagingSenderId: '830041646492',
    projectId: 'flutter-app-8662f',
    storageBucket: 'flutter-app-8662f.firebasestorage.app',
    iosBundleId: 'com.example.interHospitalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMwyPFkVe8BcX5bJMaS0h0NiG_XRxPg4o',
    appId: '1:830041646492:web:0e2d0aa4f6b14fa418d459',
    messagingSenderId: '830041646492',
    projectId: 'flutter-app-8662f',
    authDomain: 'flutter-app-8662f.firebaseapp.com',
    storageBucket: 'flutter-app-8662f.firebasestorage.app',
    measurementId: 'G-WV3PV82LW3',
  );
}
